### ISSUE TITLE
IntelliJ is not finding the the version when I add the dependency. 

### ISSUE THREAD

**Issue by Relliks44** [RoombaFromHell/Jikan#1]
IntelliJ is not neither finding version 1.0.1 nor 1.0.0. LATEST is also not working. I have no idea why this happens.
![image](https://user-images.githubusercontent.com/67743549/90156994-76b63000-dd8d-11ea-95a4-8f88d0a9b9e7.png)

**Comment by RoombaFromHell** [comment]
Hi, please make sure you've followed everything on https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages#installing-a-package the installation guide needs updating.
